### PR TITLE
Update SECURITY.md to match new definition of security vulnerability

### PR DESCRIPTION
**Pull request by Aaron-Junker**
Change link to newer definition of a security vulnerability by the MSRC.

cc: @emmairwin @jeffwilcox

### CODE REVIEW

**Comment by jeffwilcox** [comment]
Thanks @Aaron-Junker, could you also increment the "version" in the file that's in the header?

Also, @fossygirl, I thought we were discussing at one point having `aka.ms` links for this kind of content instead of hard links that evolve?

**Comment by Aaron-Junker** [comment]
@jeffwilcox   aka.ms liks really would make sense in my opinion. But I'm not able to create aka.ms links.

Question: After merging this, will the file be updated in all the repos or do you have to do this manually?

**Comment by jeffwilcox** [comment]
It will not be updated in repos, and we will not make an explicit push to update it, it's very noisy. However, net new repos will get it.

**Comment by jeffwilcox** [comment]
Aaron, can you use these links?

- https://aka.ms/security.md/definition
- aka.ms/security.md/cvd
- aka.ms/security.md/msrc/pgp
- aka.ms/security.md/msrc/create-report

I think it's OK to leave the GitHub links as-is and also the main microsoft.com/msrc link as-is

**Comment by Aaron-Junker** [comment]
@jeffwilcox I updated it and also removed the link to opensource.microsoft.com, because IMO it didn't make sense.

Could you create also an aka link to https://microsoft.com/msrc/bounty.

**Comment by jeffwilcox** [comment]
@Aaron-Junker https://aka.ms/security.md/msrc/bounty

**Comment by Aaron-Junker** [comment]
> @Aaron-Junker https://aka.ms/security.md/msrc/bounty

@jeffwilcox Done! It should now be ready to get merged.

**Comment by Pelikan212** [comment]
> Change link to newer definition of a security vulnerability by the MSRC.
> 
> cc: @emmairwin @jeffwilcox

**Comment by Pelikan212** [comment]
> Change link to newer definition of a security vulnerability by the MSRC.
> 
> cc: @emmairwin @jeffwilcox

**Comment by jeffwilcox** [comment]
... also, once ready, this technically needs to get placed into the `repo-templates` repo

**Comment by Aaron-Junker** [comment]
@jeffwilcox I don't see what's holding this from getting merged.

**Comment by jeffwilcox** [comment]
Just working on higher priority work on our side. Are you able to update the `repo-templates` version if we get this merged?

**Comment by Aaron-Junker** [comment]
> Just working on higher priority work on our side. Are you able to update the `repo-templates` version if we get this merged?

Yes I will update it too

**Comment by Aaron-Junker** [comment]
@jeffwilcox I created a PR for repo-templates here: https://github.com/microsoft/repo-templates/pull/13

**Comment by Aaron-Junker** [comment]
@jeffwilcox Could you please open it again?

**Comment by jeffwilcox** [comment]
@Aaron-Junker I have no idea why this is closing as soon as I reopen it...

**Comment by Aaron-Junker** [comment]
@jeffwilcox Seems my fork was bugged. It points to another random repository as upstream. I put the cahnges in a new fork and opened a new PR: https://github.com/microsoft/.github/pull/180

**Review by ThyagoThulyo — APPROVED** [review]

**Pull request closed without merging**
