### PR TITLE
Update cla.yml for adding prmerger test GitHub app

### PR DESCRIPTION
**Pull request by jamesyao-msft**

### CODE REVIEW

**Review by superyyrrzz — APPROVED** [review]

**Comment by superyyrrzz** [comment]
Could you help add 3 more apps?
* learn-build-service-test[bot]
* learn-build-service-ppe[bot]
* learn-build-service-prod[bot]

Thanks!

**Comment by jamesyao-msft** [comment]
> 

Added

**Review by jeffwilcox — APPROVED** [review]

**Comment by jeffwilcox** [comment]
thanks @jamesyao-msft can you let me know if this eventually corrects the issue? thanks for the report 👋🏻

**Comment by jamesyao-msft** [comment]
@jeffwilcox thanks you, do you know when this config will be deployed or when we can have a try on this issue?

**Comment by jeffwilcox** [comment]
@jamesyao-msft it's my understanding it's all relatively near real-time, no deployment

**Pull request merged**
