### PR TITLE
Update activateFabricBot.yml

### PR DESCRIPTION
**Pull request by JohannesLampel**

### CODE REVIEW

**Review by DragosDanielBoia — APPROVED** [review]

**Comment by Aaron-Junker** [comment]
What exactly is the purpose of this file?

**Comment by jeffwilcox** [comment]
@Aaron-Junker Fabric Bot is one of many GitHub App systems in use across Microsoft repositories.

**Comment by Aaron-Junker** [comment]
> @Aaron-Junker Fabric Bot is one of many GitHub App systems in use across Microsoft repositories.

I know but what does it do in this repository here?

**Comment by jeffwilcox** [comment]
@Aaron-Junker anything in the `policies` folder is made available to the repos that are in the eligibility filter. The repos in the filter can then use Fabric Bot.

See also, https://github.com/microsoft/.github/tree/main/policies

**Comment by Aaron-Junker** [comment]
> @Aaron-Junker anything in the `policies` folder is made available to the repos that are in the eligibility filter. The repos in the filter can then use Fabric Bot.
> 
> See also, https://github.com/microsoft/.github/tree/main/policies

Oh I see. But there are alot more repos that use fabric bot that the ones in the filter.

**Comment by jeffwilcox** [comment]
Yes. There's going to be a push moving toward a config-as-code model for many repos, and this is validating that newer way to use that bot, instead of what is older tech.

**Comment by Aaron-Junker** [comment]
> Yes. There's going to be a push moving toward a config-as-code model for many repos, and this is validating that newer way to use that bot, instead of what is older tech.

Oh ok. Thank you for the explenation!

**Pull request merged**
