### PR TITLE
Delete CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by bong1915016**

### CODE REVIEW

**Comment by Brandy003** [comment]
Why delete code of conduct?

**Comment by inos123** [comment]
C:\Users\HP\Documents\GitHub\docs.buddybuild.com\_js\docs.js

**Review by lzz08 — APPROVED** [review]

**Review by lzz08 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Comment by jace4511** [comment]
> Why delete code of conduct?

**Comment by jace4511** [comment]
> > Why delete code of conduct?

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Review by jace4511 — APPROVED** [review]

**Pull request closed without merging**
